# the k8s secrets
apiVersion: v1 
kind: Secret 
metadata:
    name: mongodb-secret
type: Opaque 
data:
# actual content 
# the value must be base64 encoded
    mongo-root-username: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ= 



