apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  # how many replicas of the pod u wanna create
  selector: 
    matchLabels:
      app: nginx 
  template: 
    metadata: 
      labels:
        app: nginx 
    spec:
    # we want one container on the pod nginx on port 80
      containers: 
      - name: nginx 
        image: nginx:1.16
        ports:
        - containerPort: 80